spring:
  application:
    name: gateway-api

server:
  port: 8082

ping-server:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:9092,localhost:9999
    ServerListRefreshInterval: 15000